workflows:
  release-workflow:
    name: Release
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Analyze project source
        script: flutter analyze
      - name: Run tests
        script: flutter test
