// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXmCVesQaiRM41lNpDlEmRwB43N7_q3A',
    appId: '1:616719186564:web:6ee115080969d4875ae0d1',
    messagingSenderId: '616719186564',
    projectId: 'ditonton-flutter-expert-354c7',
    authDomain: 'ditonton-flutter-expert-354c7.firebaseapp.com',
    storageBucket: 'ditonton-flutter-expert-354c7.appspot.com',
    measurementId: 'G-Y631GT5HTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9h8OMLEH_bSXyIwmLQCUe-E1uZdO5l18',
    appId: '1:616719186564:android:e3653a7ab0919a0b5ae0d1',
    messagingSenderId: '616719186564',
    projectId: 'ditonton-flutter-expert-354c7',
    storageBucket: 'ditonton-flutter-expert-354c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApzkGdq58Y2RQzVCasTwFcINEHInAfB7Y',
    appId: '1:616719186564:ios:0368f0046db88e1a5ae0d1',
    messagingSenderId: '616719186564',
    projectId: 'ditonton-flutter-expert-354c7',
    storageBucket: 'ditonton-flutter-expert-354c7.appspot.com',
    iosBundleId: 'com.example.submissionFlutterExpert',
  );
}
